### ISSUE TITLE
Image disappears and doesn't come back

### ISSUE THREAD

**Issue by anky21** [lau1944/Zoom-Drag-Rotate-ImageView#1]
In the sample app, I made the image view to take the size of the parent. 
After I used my finger to scroll from one corner of the screen to another corner to make the image smaller and disappear, released the finger, I couldn't then make the image come back.
Also, is there a way to reset the view?

**Comment by lau1944** [comment]
In general, the view itself would not disappear after you add to your parent view, maybe the view is too small or out of bounds?
If you want to reset your view, use **LayoutParams** method to set view programmatically.
Ex. in kotlin
```
ImageView.LayoutParams =  yourLayout.LayoutParams(YourWidth, YourHeight);
```

**Comment by anky21** [comment]
It seems to work fine when the image view is smaller than its parent. 
When the image view has the same size as its parent, there are a few issues:
1. I can't drag the image with one finger, instead, the image scales. This seems to be a bug to me. And I can also make the image disappear with either one finger or two fingers. 
2. When the image becomes very small, it's hard to make it bigger again. Have to use one finger but not 2 fingers.
3. When the image is gone, I can't make it come back. 

Below is the layout:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/playground"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.easystudio.rotateimageview.RotateZoomImageView
        android:id="@+id/rotate"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@drawable/money">

    </com.easystudio.rotateimageview.RotateZoomImageView>

</RelativeLayout>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20298806/85080310-32cf0080-b20c-11ea-9fbf-5c8c16c31e65.gif)

**Comment by lau1944** [comment]
Basically, when you assign your view with 'match_parent' on your viewgroup , you can't move the view again because centerX and centerY (the center position of the view) is settled and the width, height as well unless you reset the LayoutParams of your view .
You can learn more about [LayoutParams](https://developer.android.com/reference/android/view/ViewGroup.LayoutParams) here .

In our case, idk why the ImageView would disappear,but I checked that the imageView instance is still existing, I pursue that the image itself is still there, it's just too small to display.
